COMPONENT = "frontend"
PROJECT_NAME = "roboshop"
PORT           = 80
IAM_INSTANCE_PROFILE = false
SPOT_INSTANCE_COUNT = 1
INSTANCE_TYPE = "t3.micro"
INSTANCE_COUNT = 0
WORKSTATION_IP = "172.31.19.77/32"
